// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/order.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_ACCEPTED    OrderStatus = 2
	OrderStatus_ORDER_STATUS_IN_PROGRESS OrderStatus = 3
	OrderStatus_ORDER_STATUS_COMPLETED   OrderStatus = 4
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_ACCEPTED",
		3: "ORDER_STATUS_IN_PROGRESS",
		4: "ORDER_STATUS_COMPLETED",
		5: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_ACCEPTED":    2,
		"ORDER_STATUS_IN_PROGRESS": 3,
		"ORDER_STATUS_COMPLETED":   4,
		"ORDER_STATUS_CANCELLED":   5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

type WasteType int32

const (
	WasteType_WASTE_TYPE_UNSPECIFIED WasteType = 0
	WasteType_WASTE_TYPE_PAPER       WasteType = 1
	WasteType_WASTE_TYPE_PLASTIC     WasteType = 2
	WasteType_WASTE_TYPE_METAL       WasteType = 3
	WasteType_WASTE_TYPE_GLASS       WasteType = 4
	WasteType_WASTE_TYPE_ELECTRONIC  WasteType = 5
)

// Enum value maps for WasteType.
var (
	WasteType_name = map[int32]string{
		0: "WASTE_TYPE_UNSPECIFIED",
		1: "WASTE_TYPE_PAPER",
		2: "WASTE_TYPE_PLASTIC",
		3: "WASTE_TYPE_METAL",
		4: "WASTE_TYPE_GLASS",
		5: "WASTE_TYPE_ELECTRONIC",
	}
	WasteType_value = map[string]int32{
		"WASTE_TYPE_UNSPECIFIED": 0,
		"WASTE_TYPE_PAPER":       1,
		"WASTE_TYPE_PLASTIC":     2,
		"WASTE_TYPE_METAL":       3,
		"WASTE_TYPE_GLASS":       4,
		"WASTE_TYPE_ELECTRONIC":  5,
	}
)

func (x WasteType) Enum() *WasteType {
	p := new(WasteType)
	*p = x
	return p
}

func (x WasteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WasteType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_order_proto_enumTypes[1].Descriptor()
}

func (WasteType) Type() protoreflect.EnumType {
	return &file_proto_order_proto_enumTypes[1]
}

func (x WasteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WasteType.Descriptor instead.
func (WasteType) EnumDescriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

// Messages
type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CollectorId     string                 `protobuf:"bytes,3,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Status          OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=ecopoint.order.v1.OrderStatus" json:"status,omitempty"`
	WasteTypes      []WasteType            `protobuf:"varint,5,rep,packed,name=waste_types,json=wasteTypes,proto3,enum=ecopoint.order.v1.WasteType" json:"waste_types,omitempty"`
	EstimatedWeight float64                `protobuf:"fixed64,6,opt,name=estimated_weight,json=estimatedWeight,proto3" json:"estimated_weight,omitempty"`
	ActualWeight    float64                `protobuf:"fixed64,7,opt,name=actual_weight,json=actualWeight,proto3" json:"actual_weight,omitempty"`
	PickupAddress   *Address               `protobuf:"bytes,8,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	ScheduledTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	CompletedTime   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_time,json=completedTime,proto3" json:"completed_time,omitempty"`
	Notes           string                 `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Payment         *Payment               `protobuf:"bytes,12,opt,name=payment,proto3" json:"payment,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetWasteTypes() []WasteType {
	if x != nil {
		return x.WasteTypes
	}
	return nil
}

func (x *Order) GetEstimatedWeight() float64 {
	if x != nil {
		return x.EstimatedWeight
	}
	return 0
}

func (x *Order) GetActualWeight() float64 {
	if x != nil {
		return x.ActualWeight
	}
	return 0
}

func (x *Order) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *Order) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *Order) GetCompletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedTime
	}
	return nil
}

func (x *Order) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Order) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	IsPaid        bool                   `protobuf:"varint,4,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
	PaymentTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=payment_time,json=paymentTime,proto3" json:"payment_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_proto_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{1}
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Payment) GetIsPaid() bool {
	if x != nil {
		return x.IsPaid
	}
	return false
}

func (x *Payment) GetPaymentTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PaymentTime
	}
	return nil
}

// Request/Response messages
type CreateOrderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CustomerId      string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	WasteTypes      []WasteType            `protobuf:"varint,2,rep,packed,name=waste_types,json=wasteTypes,proto3,enum=ecopoint.order.v1.WasteType" json:"waste_types,omitempty"`
	EstimatedWeight float64                `protobuf:"fixed64,3,opt,name=estimated_weight,json=estimatedWeight,proto3" json:"estimated_weight,omitempty"`
	PickupAddress   *Address               `protobuf:"bytes,4,opt,name=pickup_address,json=pickupAddress,proto3" json:"pickup_address,omitempty"`
	ScheduledTime   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	Notes           string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetWasteTypes() []WasteType {
	if x != nil {
		return x.WasteTypes
	}
	return nil
}

func (x *CreateOrderRequest) GetEstimatedWeight() float64 {
	if x != nil {
		return x.EstimatedWeight
	}
	return 0
}

func (x *CreateOrderRequest) GetPickupAddress() *Address {
	if x != nil {
		return x.PickupAddress
	}
	return nil
}

func (x *CreateOrderRequest) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *CreateOrderRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_proto_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetUserOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      string                 `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersRequest) Reset() {
	*x = GetUserOrdersRequest{}
	mi := &file_proto_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersRequest) ProtoMessage() {}

func (x *GetUserOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetUserOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserOrdersRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type GetUserOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrdersResponse) Reset() {
	*x = GetUserOrdersResponse{}
	mi := &file_proto_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrdersResponse) ProtoMessage() {}

func (x *GetUserOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetAvailableOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableOrdersRequest) Reset() {
	*x = GetAvailableOrdersRequest{}
	mi := &file_proto_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableOrdersRequest) ProtoMessage() {}

func (x *GetAvailableOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetAvailableOrdersRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type GetAvailableOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableOrdersResponse) Reset() {
	*x = GetAvailableOrdersResponse{}
	mi := &file_proto_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableOrdersResponse) ProtoMessage() {}

func (x *GetAvailableOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetAvailableOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CollectorId   string                 `protobuf:"bytes,2,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{10}
}

func (x *AcceptOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AcceptOrderRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type AcceptOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderResponse) Reset() {
	*x = AcceptOrderResponse{}
	mi := &file_proto_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderResponse) ProtoMessage() {}

func (x *AcceptOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderResponse.ProtoReflect.Descriptor instead.
func (*AcceptOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{11}
}

func (x *AcceptOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcceptOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=ecopoint.order.v1.OrderStatus" json:"status,omitempty"`
	ActualWeight  float64                `protobuf:"fixed64,4,opt,name=actual_weight,json=actualWeight,proto3" json:"actual_weight,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_proto_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *UpdateOrderStatusRequest) GetActualWeight() float64 {
	if x != nil {
		return x.ActualWeight
	}
	return 0
}

func (x *UpdateOrderStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_proto_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOrderStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateOrderStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CompleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CollectorId   string                 `protobuf:"bytes,2,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	ActualWeight  float64                `protobuf:"fixed64,3,opt,name=actual_weight,json=actualWeight,proto3" json:"actual_weight,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderRequest) Reset() {
	*x = CompleteOrderRequest{}
	mi := &file_proto_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderRequest) ProtoMessage() {}

func (x *CompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*CompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{14}
}

func (x *CompleteOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CompleteOrderRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *CompleteOrderRequest) GetActualWeight() float64 {
	if x != nil {
		return x.ActualWeight
	}
	return 0
}

func (x *CompleteOrderRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CompleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOrderResponse) Reset() {
	*x = CompleteOrderResponse{}
	mi := &file_proto_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOrderResponse) ProtoMessage() {}

func (x *CompleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOrderResponse.ProtoReflect.Descriptor instead.
func (*CompleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_proto_rawDescGZIP(), []int{15}
}

func (x *CompleteOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_order_proto protoreflect.FileDescriptor

const file_proto_order_proto_rawDesc = "" +
	"\n" +
	"\x11proto/order.proto\x12\x11ecopoint.order.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12proto/shared.proto\"\xae\x05\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fcollector_id\x18\x03 \x01(\tR\vcollectorId\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.ecopoint.order.v1.OrderStatusR\x06status\x12=\n" +
	"\vwaste_types\x18\x05 \x03(\x0e2\x1c.ecopoint.order.v1.WasteTypeR\n" +
	"wasteTypes\x12)\n" +
	"\x10estimated_weight\x18\x06 \x01(\x01R\x0festimatedWeight\x12#\n" +
	"\ractual_weight\x18\a \x01(\x01R\factualWeight\x12B\n" +
	"\x0epickup_address\x18\b \x01(\v2\x1b.ecopoint.shared.v1.AddressR\rpickupAddress\x12A\n" +
	"\x0escheduled_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12A\n" +
	"\x0ecompleted_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rcompletedTime\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x124\n" +
	"\apayment\x18\f \x01(\v2\x1a.ecopoint.order.v1.PaymentR\apayment\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xad\x01\n" +
	"\aPayment\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x17\n" +
	"\ais_paid\x18\x04 \x01(\bR\x06isPaid\x12=\n" +
	"\fpayment_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vpaymentTime\"\xbc\x02\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12=\n" +
	"\vwaste_types\x18\x02 \x03(\x0e2\x1c.ecopoint.order.v1.WasteTypeR\n" +
	"wasteTypes\x12)\n" +
	"\x10estimated_weight\x18\x03 \x01(\x01R\x0festimatedWeight\x12B\n" +
	"\x0epickup_address\x18\x04 \x01(\v2\x1b.ecopoint.shared.v1.AddressR\rpickupAddress\x12A\n" +
	"\x0escheduled_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\"E\n" +
	"\x13CreateOrderResponse\x12.\n" +
	"\x05order\x18\x01 \x01(\v2\x18.ecopoint.order.v1.OrderR\x05order\"E\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\x10GetOrderResponse\x12.\n" +
	"\x05order\x18\x01 \x01(\v2\x18.ecopoint.order.v1.OrderR\x05order\"L\n" +
	"\x14GetUserOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_type\x18\x02 \x01(\tR\buserType\"I\n" +
	"\x15GetUserOrdersResponse\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.ecopoint.order.v1.OrderR\x06orders\">\n" +
	"\x19GetAvailableOrdersRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"N\n" +
	"\x1aGetAvailableOrdersResponse\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.ecopoint.order.v1.OrderR\x06orders\"R\n" +
	"\x12AcceptOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\fcollector_id\x18\x02 \x01(\tR\vcollectorId\"I\n" +
	"\x13AcceptOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc1\x01\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1e.ecopoint.order.v1.OrderStatusR\x06status\x12#\n" +
	"\ractual_weight\x18\x04 \x01(\x01R\factualWeight\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"O\n" +
	"\x19UpdateOrderStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8f\x01\n" +
	"\x14CompleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\fcollector_id\x18\x02 \x01(\tR\vcollectorId\x12#\n" +
	"\ractual_weight\x18\x03 \x01(\x01R\factualWeight\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"K\n" +
	"\x15CompleteOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xb6\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x19\n" +
	"\x15ORDER_STATUS_ACCEPTED\x10\x02\x12\x1c\n" +
	"\x18ORDER_STATUS_IN_PROGRESS\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x05*\x9c\x01\n" +
	"\tWasteType\x12\x1a\n" +
	"\x16WASTE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10WASTE_TYPE_PAPER\x10\x01\x12\x16\n" +
	"\x12WASTE_TYPE_PLASTIC\x10\x02\x12\x14\n" +
	"\x10WASTE_TYPE_METAL\x10\x03\x12\x14\n" +
	"\x10WASTE_TYPE_GLASS\x10\x04\x12\x19\n" +
	"\x15WASTE_TYPE_ELECTRONIC\x10\x052\xca\x05\n" +
	"\fOrderService\x12\\\n" +
	"\vCreateOrder\x12%.ecopoint.order.v1.CreateOrderRequest\x1a&.ecopoint.order.v1.CreateOrderResponse\x12S\n" +
	"\bGetOrder\x12\".ecopoint.order.v1.GetOrderRequest\x1a#.ecopoint.order.v1.GetOrderResponse\x12b\n" +
	"\rGetUserOrders\x12'.ecopoint.order.v1.GetUserOrdersRequest\x1a(.ecopoint.order.v1.GetUserOrdersResponse\x12q\n" +
	"\x12GetAvailableOrders\x12,.ecopoint.order.v1.GetAvailableOrdersRequest\x1a-.ecopoint.order.v1.GetAvailableOrdersResponse\x12\\\n" +
	"\vAcceptOrder\x12%.ecopoint.order.v1.AcceptOrderRequest\x1a&.ecopoint.order.v1.AcceptOrderResponse\x12n\n" +
	"\x11UpdateOrderStatus\x12+.ecopoint.order.v1.UpdateOrderStatusRequest\x1a,.ecopoint.order.v1.UpdateOrderStatusResponse\x12b\n" +
	"\rCompleteOrder\x12'.ecopoint.order.v1.CompleteOrderRequest\x1a(.ecopoint.order.v1.CompleteOrderResponseB\x18Z\x16ecopoint-backend/protob\x06proto3"

var (
	file_proto_order_proto_rawDescOnce sync.Once
	file_proto_order_proto_rawDescData []byte
)

func file_proto_order_proto_rawDescGZIP() []byte {
	file_proto_order_proto_rawDescOnce.Do(func() {
		file_proto_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)))
	})
	return file_proto_order_proto_rawDescData
}

var file_proto_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_order_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_order_proto_goTypes = []any{
	(OrderStatus)(0),                   // 0: ecopoint.order.v1.OrderStatus
	(WasteType)(0),                     // 1: ecopoint.order.v1.WasteType
	(*Order)(nil),                      // 2: ecopoint.order.v1.Order
	(*Payment)(nil),                    // 3: ecopoint.order.v1.Payment
	(*CreateOrderRequest)(nil),         // 4: ecopoint.order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),        // 5: ecopoint.order.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),            // 6: ecopoint.order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),           // 7: ecopoint.order.v1.GetOrderResponse
	(*GetUserOrdersRequest)(nil),       // 8: ecopoint.order.v1.GetUserOrdersRequest
	(*GetUserOrdersResponse)(nil),      // 9: ecopoint.order.v1.GetUserOrdersResponse
	(*GetAvailableOrdersRequest)(nil),  // 10: ecopoint.order.v1.GetAvailableOrdersRequest
	(*GetAvailableOrdersResponse)(nil), // 11: ecopoint.order.v1.GetAvailableOrdersResponse
	(*AcceptOrderRequest)(nil),         // 12: ecopoint.order.v1.AcceptOrderRequest
	(*AcceptOrderResponse)(nil),        // 13: ecopoint.order.v1.AcceptOrderResponse
	(*UpdateOrderStatusRequest)(nil),   // 14: ecopoint.order.v1.UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil),  // 15: ecopoint.order.v1.UpdateOrderStatusResponse
	(*CompleteOrderRequest)(nil),       // 16: ecopoint.order.v1.CompleteOrderRequest
	(*CompleteOrderResponse)(nil),      // 17: ecopoint.order.v1.CompleteOrderResponse
	(*Address)(nil),                    // 18: ecopoint.shared.v1.Address
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_proto_order_proto_depIdxs = []int32{
	0,  // 0: ecopoint.order.v1.Order.status:type_name -> ecopoint.order.v1.OrderStatus
	1,  // 1: ecopoint.order.v1.Order.waste_types:type_name -> ecopoint.order.v1.WasteType
	18, // 2: ecopoint.order.v1.Order.pickup_address:type_name -> ecopoint.shared.v1.Address
	19, // 3: ecopoint.order.v1.Order.scheduled_time:type_name -> google.protobuf.Timestamp
	19, // 4: ecopoint.order.v1.Order.completed_time:type_name -> google.protobuf.Timestamp
	3,  // 5: ecopoint.order.v1.Order.payment:type_name -> ecopoint.order.v1.Payment
	19, // 6: ecopoint.order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: ecopoint.order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	19, // 8: ecopoint.order.v1.Payment.payment_time:type_name -> google.protobuf.Timestamp
	1,  // 9: ecopoint.order.v1.CreateOrderRequest.waste_types:type_name -> ecopoint.order.v1.WasteType
	18, // 10: ecopoint.order.v1.CreateOrderRequest.pickup_address:type_name -> ecopoint.shared.v1.Address
	19, // 11: ecopoint.order.v1.CreateOrderRequest.scheduled_time:type_name -> google.protobuf.Timestamp
	2,  // 12: ecopoint.order.v1.CreateOrderResponse.order:type_name -> ecopoint.order.v1.Order
	2,  // 13: ecopoint.order.v1.GetOrderResponse.order:type_name -> ecopoint.order.v1.Order
	2,  // 14: ecopoint.order.v1.GetUserOrdersResponse.orders:type_name -> ecopoint.order.v1.Order
	2,  // 15: ecopoint.order.v1.GetAvailableOrdersResponse.orders:type_name -> ecopoint.order.v1.Order
	0,  // 16: ecopoint.order.v1.UpdateOrderStatusRequest.status:type_name -> ecopoint.order.v1.OrderStatus
	4,  // 17: ecopoint.order.v1.OrderService.CreateOrder:input_type -> ecopoint.order.v1.CreateOrderRequest
	6,  // 18: ecopoint.order.v1.OrderService.GetOrder:input_type -> ecopoint.order.v1.GetOrderRequest
	8,  // 19: ecopoint.order.v1.OrderService.GetUserOrders:input_type -> ecopoint.order.v1.GetUserOrdersRequest
	10, // 20: ecopoint.order.v1.OrderService.GetAvailableOrders:input_type -> ecopoint.order.v1.GetAvailableOrdersRequest
	12, // 21: ecopoint.order.v1.OrderService.AcceptOrder:input_type -> ecopoint.order.v1.AcceptOrderRequest
	14, // 22: ecopoint.order.v1.OrderService.UpdateOrderStatus:input_type -> ecopoint.order.v1.UpdateOrderStatusRequest
	16, // 23: ecopoint.order.v1.OrderService.CompleteOrder:input_type -> ecopoint.order.v1.CompleteOrderRequest
	5,  // 24: ecopoint.order.v1.OrderService.CreateOrder:output_type -> ecopoint.order.v1.CreateOrderResponse
	7,  // 25: ecopoint.order.v1.OrderService.GetOrder:output_type -> ecopoint.order.v1.GetOrderResponse
	9,  // 26: ecopoint.order.v1.OrderService.GetUserOrders:output_type -> ecopoint.order.v1.GetUserOrdersResponse
	11, // 27: ecopoint.order.v1.OrderService.GetAvailableOrders:output_type -> ecopoint.order.v1.GetAvailableOrdersResponse
	13, // 28: ecopoint.order.v1.OrderService.AcceptOrder:output_type -> ecopoint.order.v1.AcceptOrderResponse
	15, // 29: ecopoint.order.v1.OrderService.UpdateOrderStatus:output_type -> ecopoint.order.v1.UpdateOrderStatusResponse
	17, // 30: ecopoint.order.v1.OrderService.CompleteOrder:output_type -> ecopoint.order.v1.CompleteOrderResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_order_proto_init() }
func file_proto_order_proto_init() {
	if File_proto_order_proto != nil {
		return
	}
	file_proto_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_proto_rawDesc), len(file_proto_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_proto_goTypes,
		DependencyIndexes: file_proto_order_proto_depIdxs,
		EnumInfos:         file_proto_order_proto_enumTypes,
		MessageInfos:      file_proto_order_proto_msgTypes,
	}.Build()
	File_proto_order_proto = out.File
	file_proto_order_proto_goTypes = nil
	file_proto_order_proto_depIdxs = nil
}
