// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybscf21-Y1HZen-Dkkn82QrGdtHq1yRE',
    appId: '1:742752087052:web:8548c6f1aab5064e3d9229',
    messagingSenderId: '742752087052',
    projectId: 'ecopoint-v1',
    authDomain: 'ecopoint-v1.firebaseapp.com',
    storageBucket: 'ecopoint-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD00573VtnNgNCnDi_xL8cVS5noglcAGpo',
    appId: '1:742752087052:android:d2a60ca104c832773d9229',
    messagingSenderId: '742752087052',
    projectId: 'ecopoint-v1',
    storageBucket: 'ecopoint-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5YfXW5QFiZnpuscnFeOncxr3X-QRT3jQ',
    appId: '1:742752087052:ios:814c54be47fc5e6a3d9229',
    messagingSenderId: '742752087052',
    projectId: 'ecopoint-v1',
    storageBucket: 'ecopoint-v1.firebasestorage.app',
    iosBundleId: 'com.example.collectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5YfXW5QFiZnpuscnFeOncxr3X-QRT3jQ',
    appId: '1:742752087052:ios:814c54be47fc5e6a3d9229',
    messagingSenderId: '742752087052',
    projectId: 'ecopoint-v1',
    storageBucket: 'ecopoint-v1.firebasestorage.app',
    iosBundleId: 'com.example.collectorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBybscf21-Y1HZen-Dkkn82QrGdtHq1yRE',
    appId: '1:742752087052:web:edd48145eb9805943d9229',
    messagingSenderId: '742752087052',
    projectId: 'ecopoint-v1',
    authDomain: 'ecopoint-v1.firebaseapp.com',
    storageBucket: 'ecopoint-v1.firebasestorage.app',
  );
}
