// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/collecting.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_collecting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullText      string                 `protobuf:"bytes,1,opt,name=full_text,json=fullText,proto3" json:"full_text,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,3,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_collecting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetFullText() string {
	if x != nil {
		return x.FullText
	}
	return ""
}

func (x *Address) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Address) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type CustomerSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerSnapshot) Reset() {
	*x = CustomerSnapshot{}
	mi := &file_proto_collecting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerSnapshot) ProtoMessage() {}

func (x *CustomerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerSnapshot.ProtoReflect.Descriptor instead.
func (*CustomerSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerSnapshot) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CustomerSnapshot) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type WasteItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WasteItem) Reset() {
	*x = WasteItem{}
	mi := &file_proto_collecting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasteItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasteItem) ProtoMessage() {}

func (x *WasteItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasteItem.ProtoReflect.Descriptor instead.
func (*WasteItem) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{3}
}

func (x *WasteItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WasteItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Order struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId          string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AcceptedBy          string                 `protobuf:"bytes,4,opt,name=accepted_by,json=acceptedBy,proto3" json:"accepted_by,omitempty"`
	PickAddressSnapshot *Address               `protobuf:"bytes,5,opt,name=pick_address_snapshot,json=pickAddressSnapshot,proto3" json:"pick_address_snapshot,omitempty"`
	CustomerSnapshot    *CustomerSnapshot      `protobuf:"bytes,6,opt,name=customer_snapshot,json=customerSnapshot,proto3" json:"customer_snapshot,omitempty"`
	Items               []*WasteItem           `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	TotalWeight         float64                `protobuf:"fixed64,8,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	EstimatedPrice      float64                `protobuf:"fixed64,9,opt,name=estimated_price,json=estimatedPrice,proto3" json:"estimated_price,omitempty"`
	DistanceKm          float64                `protobuf:"fixed64,10,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	EtaMinutes          int32                  `protobuf:"varint,11,opt,name=eta_minutes,json=etaMinutes,proto3" json:"eta_minutes,omitempty"`
	Note                string                 `protobuf:"bytes,12,opt,name=note,proto3" json:"note,omitempty"`
	Version             int64                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_collecting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetAcceptedBy() string {
	if x != nil {
		return x.AcceptedBy
	}
	return ""
}

func (x *Order) GetPickAddressSnapshot() *Address {
	if x != nil {
		return x.PickAddressSnapshot
	}
	return nil
}

func (x *Order) GetCustomerSnapshot() *CustomerSnapshot {
	if x != nil {
		return x.CustomerSnapshot
	}
	return nil
}

func (x *Order) GetItems() []*WasteItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalWeight() float64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *Order) GetEstimatedPrice() float64 {
	if x != nil {
		return x.EstimatedPrice
	}
	return 0
}

func (x *Order) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *Order) GetEtaMinutes() int32 {
	if x != nil {
		return x.EtaMinutes
	}
	return 0
}

func (x *Order) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Order) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CreateOrderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomerId       string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PickAddress      *Address               `protobuf:"bytes,2,opt,name=pick_address,json=pickAddress,proto3" json:"pick_address,omitempty"`
	CustomerSnapshot *CustomerSnapshot      `protobuf:"bytes,3,opt,name=customer_snapshot,json=customerSnapshot,proto3" json:"customer_snapshot,omitempty"`
	Items            []*WasteItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	TotalWeight      float64                `protobuf:"fixed64,5,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	EstimatedPrice   float64                `protobuf:"fixed64,6,opt,name=estimated_price,json=estimatedPrice,proto3" json:"estimated_price,omitempty"`
	Note             string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_collecting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateOrderRequest) GetPickAddress() *Address {
	if x != nil {
		return x.PickAddress
	}
	return nil
}

func (x *CreateOrderRequest) GetCustomerSnapshot() *CustomerSnapshot {
	if x != nil {
		return x.CustomerSnapshot
	}
	return nil
}

func (x *CreateOrderRequest) GetItems() []*WasteItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetTotalWeight() float64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *CreateOrderRequest) GetEstimatedPrice() float64 {
	if x != nil {
		return x.EstimatedPrice
	}
	return 0
}

func (x *CreateOrderRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ListAvailableOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableOrdersRequest) Reset() {
	*x = ListAvailableOrdersRequest{}
	mi := &file_proto_collecting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableOrdersRequest) ProtoMessage() {}

func (x *ListAvailableOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{6}
}

func (x *ListAvailableOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAvailableOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailableOrdersResponse) Reset() {
	*x = ListAvailableOrdersResponse{}
	mi := &file_proto_collecting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableOrdersResponse) ProtoMessage() {}

func (x *ListAvailableOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{7}
}

func (x *ListAvailableOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type AcceptOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CollectorId   string                 `protobuf:"bytes,2,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptOrderRequest) Reset() {
	*x = AcceptOrderRequest{}
	mi := &file_proto_collecting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptOrderRequest) ProtoMessage() {}

func (x *AcceptOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptOrderRequest.ProtoReflect.Descriptor instead.
func (*AcceptOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AcceptOrderRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CollectorId   string                 `protobuf:"bytes,3,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_proto_collecting_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOrderStatusRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_collecting_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{10}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListMyActiveOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollectorId   string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyActiveOrdersRequest) Reset() {
	*x = ListMyActiveOrdersRequest{}
	mi := &file_proto_collecting_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyActiveOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyActiveOrdersRequest) ProtoMessage() {}

func (x *ListMyActiveOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyActiveOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListMyActiveOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{11}
}

func (x *ListMyActiveOrdersRequest) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

type ListMyOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyOrdersRequest) Reset() {
	*x = ListMyOrdersRequest{}
	mi := &file_proto_collecting_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyOrdersRequest) ProtoMessage() {}

func (x *ListMyOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListMyOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{12}
}

func (x *ListMyOrdersRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListMyOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyOrdersRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_proto_collecting_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collecting_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_collecting_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_proto_collecting_proto protoreflect.FileDescriptor

const file_proto_collecting_proto_rawDesc = "" +
	"\n" +
	"\x16proto/collecting.proto\x12\x16ecopoint.collecting.v1\"\a\n" +
	"\x05Empty\"J\n" +
	"\aAddress\x12\x1b\n" +
	"\tfull_text\x18\x01 \x01(\tR\bfullText\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x03 \x01(\x01R\x03lng\"K\n" +
	"\x10CustomerSnapshot\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"7\n" +
	"\tWasteItem\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"\x92\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vaccepted_by\x18\x04 \x01(\tR\n" +
	"acceptedBy\x12S\n" +
	"\x15pick_address_snapshot\x18\x05 \x01(\v2\x1f.ecopoint.collecting.v1.AddressR\x13pickAddressSnapshot\x12U\n" +
	"\x11customer_snapshot\x18\x06 \x01(\v2(.ecopoint.collecting.v1.CustomerSnapshotR\x10customerSnapshot\x127\n" +
	"\x05items\x18\a \x03(\v2!.ecopoint.collecting.v1.WasteItemR\x05items\x12!\n" +
	"\ftotal_weight\x18\b \x01(\x01R\vtotalWeight\x12'\n" +
	"\x0festimated_price\x18\t \x01(\x01R\x0eestimatedPrice\x12\x1f\n" +
	"\vdistance_km\x18\n" +
	" \x01(\x01R\n" +
	"distanceKm\x12\x1f\n" +
	"\veta_minutes\x18\v \x01(\x05R\n" +
	"etaMinutes\x12\x12\n" +
	"\x04note\x18\f \x01(\tR\x04note\x12\x18\n" +
	"\aversion\x18\r \x01(\x03R\aversion\"\xe9\x02\n" +
	"\x12CreateOrderRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12B\n" +
	"\fpick_address\x18\x02 \x01(\v2\x1f.ecopoint.collecting.v1.AddressR\vpickAddress\x12U\n" +
	"\x11customer_snapshot\x18\x03 \x01(\v2(.ecopoint.collecting.v1.CustomerSnapshotR\x10customerSnapshot\x127\n" +
	"\x05items\x18\x04 \x03(\v2!.ecopoint.collecting.v1.WasteItemR\x05items\x12!\n" +
	"\ftotal_weight\x18\x05 \x01(\x01R\vtotalWeight\x12'\n" +
	"\x0festimated_price\x18\x06 \x01(\x01R\x0eestimatedPrice\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\"2\n" +
	"\x1aListAvailableOrdersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"T\n" +
	"\x1bListAvailableOrdersResponse\x125\n" +
	"\x06orders\x18\x01 \x03(\v2\x1d.ecopoint.collecting.v1.OrderR\x06orders\"R\n" +
	"\x12AcceptOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\fcollector_id\x18\x02 \x01(\tR\vcollectorId\"p\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fcollector_id\x18\x03 \x01(\tR\vcollectorId\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\">\n" +
	"\x19ListMyActiveOrdersRequest\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\"^\n" +
	"\x13ListMyOrdersRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"K\n" +
	"\x12ListOrdersResponse\x125\n" +
	"\x06orders\x18\x01 \x03(\v2\x1d.ecopoint.collecting.v1.OrderR\x06orders2\xdf\x05\n" +
	"\x11CollectingService\x12X\n" +
	"\vCreateOrder\x12*.ecopoint.collecting.v1.CreateOrderRequest\x1a\x1d.ecopoint.collecting.v1.Order\x12~\n" +
	"\x13ListAvailableOrders\x122.ecopoint.collecting.v1.ListAvailableOrdersRequest\x1a3.ecopoint.collecting.v1.ListAvailableOrdersResponse\x12X\n" +
	"\vAcceptOrder\x12*.ecopoint.collecting.v1.AcceptOrderRequest\x1a\x1d.ecopoint.collecting.v1.Order\x12d\n" +
	"\x11UpdateOrderStatus\x120.ecopoint.collecting.v1.UpdateOrderStatusRequest\x1a\x1d.ecopoint.collecting.v1.Order\x12R\n" +
	"\bGetOrder\x12'.ecopoint.collecting.v1.GetOrderRequest\x1a\x1d.ecopoint.collecting.v1.Order\x12s\n" +
	"\x12ListMyActiveOrders\x121.ecopoint.collecting.v1.ListMyActiveOrdersRequest\x1a*.ecopoint.collecting.v1.ListOrdersResponse\x12g\n" +
	"\fListMyOrders\x12+.ecopoint.collecting.v1.ListMyOrdersRequest\x1a*.ecopoint.collecting.v1.ListOrdersResponseB#Z!ecopoint/collecting_service/pb;pbb\x06proto3"

var (
	file_proto_collecting_proto_rawDescOnce sync.Once
	file_proto_collecting_proto_rawDescData []byte
)

func file_proto_collecting_proto_rawDescGZIP() []byte {
	file_proto_collecting_proto_rawDescOnce.Do(func() {
		file_proto_collecting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collecting_proto_rawDesc), len(file_proto_collecting_proto_rawDesc)))
	})
	return file_proto_collecting_proto_rawDescData
}

var file_proto_collecting_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_collecting_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: ecopoint.collecting.v1.Empty
	(*Address)(nil),                     // 1: ecopoint.collecting.v1.Address
	(*CustomerSnapshot)(nil),            // 2: ecopoint.collecting.v1.CustomerSnapshot
	(*WasteItem)(nil),                   // 3: ecopoint.collecting.v1.WasteItem
	(*Order)(nil),                       // 4: ecopoint.collecting.v1.Order
	(*CreateOrderRequest)(nil),          // 5: ecopoint.collecting.v1.CreateOrderRequest
	(*ListAvailableOrdersRequest)(nil),  // 6: ecopoint.collecting.v1.ListAvailableOrdersRequest
	(*ListAvailableOrdersResponse)(nil), // 7: ecopoint.collecting.v1.ListAvailableOrdersResponse
	(*AcceptOrderRequest)(nil),          // 8: ecopoint.collecting.v1.AcceptOrderRequest
	(*UpdateOrderStatusRequest)(nil),    // 9: ecopoint.collecting.v1.UpdateOrderStatusRequest
	(*GetOrderRequest)(nil),             // 10: ecopoint.collecting.v1.GetOrderRequest
	(*ListMyActiveOrdersRequest)(nil),   // 11: ecopoint.collecting.v1.ListMyActiveOrdersRequest
	(*ListMyOrdersRequest)(nil),         // 12: ecopoint.collecting.v1.ListMyOrdersRequest
	(*ListOrdersResponse)(nil),          // 13: ecopoint.collecting.v1.ListOrdersResponse
}
var file_proto_collecting_proto_depIdxs = []int32{
	1,  // 0: ecopoint.collecting.v1.Order.pick_address_snapshot:type_name -> ecopoint.collecting.v1.Address
	2,  // 1: ecopoint.collecting.v1.Order.customer_snapshot:type_name -> ecopoint.collecting.v1.CustomerSnapshot
	3,  // 2: ecopoint.collecting.v1.Order.items:type_name -> ecopoint.collecting.v1.WasteItem
	1,  // 3: ecopoint.collecting.v1.CreateOrderRequest.pick_address:type_name -> ecopoint.collecting.v1.Address
	2,  // 4: ecopoint.collecting.v1.CreateOrderRequest.customer_snapshot:type_name -> ecopoint.collecting.v1.CustomerSnapshot
	3,  // 5: ecopoint.collecting.v1.CreateOrderRequest.items:type_name -> ecopoint.collecting.v1.WasteItem
	4,  // 6: ecopoint.collecting.v1.ListAvailableOrdersResponse.orders:type_name -> ecopoint.collecting.v1.Order
	4,  // 7: ecopoint.collecting.v1.ListOrdersResponse.orders:type_name -> ecopoint.collecting.v1.Order
	5,  // 8: ecopoint.collecting.v1.CollectingService.CreateOrder:input_type -> ecopoint.collecting.v1.CreateOrderRequest
	6,  // 9: ecopoint.collecting.v1.CollectingService.ListAvailableOrders:input_type -> ecopoint.collecting.v1.ListAvailableOrdersRequest
	8,  // 10: ecopoint.collecting.v1.CollectingService.AcceptOrder:input_type -> ecopoint.collecting.v1.AcceptOrderRequest
	9,  // 11: ecopoint.collecting.v1.CollectingService.UpdateOrderStatus:input_type -> ecopoint.collecting.v1.UpdateOrderStatusRequest
	10, // 12: ecopoint.collecting.v1.CollectingService.GetOrder:input_type -> ecopoint.collecting.v1.GetOrderRequest
	11, // 13: ecopoint.collecting.v1.CollectingService.ListMyActiveOrders:input_type -> ecopoint.collecting.v1.ListMyActiveOrdersRequest
	12, // 14: ecopoint.collecting.v1.CollectingService.ListMyOrders:input_type -> ecopoint.collecting.v1.ListMyOrdersRequest
	4,  // 15: ecopoint.collecting.v1.CollectingService.CreateOrder:output_type -> ecopoint.collecting.v1.Order
	7,  // 16: ecopoint.collecting.v1.CollectingService.ListAvailableOrders:output_type -> ecopoint.collecting.v1.ListAvailableOrdersResponse
	4,  // 17: ecopoint.collecting.v1.CollectingService.AcceptOrder:output_type -> ecopoint.collecting.v1.Order
	4,  // 18: ecopoint.collecting.v1.CollectingService.UpdateOrderStatus:output_type -> ecopoint.collecting.v1.Order
	4,  // 19: ecopoint.collecting.v1.CollectingService.GetOrder:output_type -> ecopoint.collecting.v1.Order
	13, // 20: ecopoint.collecting.v1.CollectingService.ListMyActiveOrders:output_type -> ecopoint.collecting.v1.ListOrdersResponse
	13, // 21: ecopoint.collecting.v1.CollectingService.ListMyOrders:output_type -> ecopoint.collecting.v1.ListOrdersResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_collecting_proto_init() }
func file_proto_collecting_proto_init() {
	if File_proto_collecting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collecting_proto_rawDesc), len(file_proto_collecting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collecting_proto_goTypes,
		DependencyIndexes: file_proto_collecting_proto_depIdxs,
		MessageInfos:      file_proto_collecting_proto_msgTypes,
	}.Build()
	File_proto_collecting_proto = out.File
	file_proto_collecting_proto_goTypes = nil
	file_proto_collecting_proto_depIdxs = nil
}
